### ISSUE TITLE
NPE when reference doesn't contain external file name

### ISSUE THREAD

**Issue by pragmaticway** [networknt/openapi-bundler#3]
When my openapi.yaml doesn't contain external file in the reference, I'm getting NPE:

My openapi.yaml
```
openapi: 3.0.0

paths: 
  /test:
    get:
      operationId: test
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#MyObj'
```
The tool output:
```
refKey = #MyObj
null map
java.lang.NullPointerException
        at com.networknt.openapi.Bundler.isRefMapObject(Bundler.java:242)
        at com.networknt.openapi.Bundler.handlerPointer(Bundler.java:200)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:299)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.resolveMap(Bundler.java:304)
        at com.networknt.openapi.Bundler.run(Bundler.java:104)
        at com.networknt.openapi.Bundler.main(Bundler.java:59)
OpenAPI Bundler: Bundle complete...
```

**Comment by ddobrin** [comment]
I will look into it

**Comment by ddobrin** [comment]
The problem is that it doesn't resolve the definition locally, as there is no external file specified. 
the error message was not indicative.
Fixed

**Comment by pragmaticway** [comment]
Thank you! Now it fluently reports the error:

`ERROR: Could not resolve reference locally in components for key #MyObj. Please check your components section.`

Please close this issue as fixed.
